# Generated by Django 4.0.4 on 2022-05-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ganspa', '0002_account_delete_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='coffee',
            field=models.BooleanField(max_length=100),
        ),
    ]
