# Generated by Django 4.0.4 on 2022-05-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ganspa', '0003_alter_account_coffee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=200)),
                ('gender', models.BooleanField()),
                ('age', models.IntegerField(default=0)),
                ('birthday', models.DateField()),
            ],
        ),
    ]
