# Generated by Django 4.0.4 on 2022-05-04 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ganspa', '0004_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='coffeelike',
        ),
        migrations.RemoveField(
            model_name='account',
            name='name',
        ),
        migrations.AddField(
            model_name='account',
            name='birthday',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
