# Generated by Django 4.0.4 on 2022-05-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ganspa', '0005_remove_account_coffeelike_remove_account_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='birthday',
        ),
        migrations.AddField(
            model_name='account',
            name='coffee_like',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='fullname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
